//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModManager.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModManager.Locale.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Button_Apply {
            get {
                return ResourceManager.GetString("Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Path to Clipboard....
        /// </summary>
        public static string Button_CopyPathToClipboard {
            get {
                return ResourceManager.GetString("Button_CopyPathToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Button_Download {
            get {
                return ResourceManager.GetString("Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Directory Opus....
        /// </summary>
        public static string Button_OpenInDopus {
            get {
                return ResourceManager.GetString("Button_OpenInDopus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in File Explorer....
        /// </summary>
        public static string Button_OpenInFileExplorer {
            get {
                return ResourceManager.GetString("Button_OpenInFileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Button_Rename {
            get {
                return ResourceManager.GetString("Button_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Button_Skip {
            get {
                return ResourceManager.GetString("Button_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Order.
        /// </summary>
        public static string CommandBar_Button_AddNewOrder_ToolTip {
            get {
                return ResourceManager.GetString("CommandBar_Button_AddNewOrder_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate a Coffee....
        /// </summary>
        public static string CommandBar_Button_Donate_ToolTip {
            get {
                return ResourceManager.GetString("CommandBar_Button_Donate_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Active Mods to Zip.
        /// </summary>
        public static string CommandBar_Button_ExportActiveModsToZip_ToolTip {
            get {
                return ResourceManager.GetString("CommandBar_Button_ExportActiveModsToZip_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Active Mods to Zip As....
        /// </summary>
        public static string CommandBar_Button_ExportOrderToArchive_ToolTip {
            get {
                return ResourceManager.GetString("CommandBar_Button_ExportOrderToArchive_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Order to Game.
        /// </summary>
        public static string CommandBar_Button_ExportOrderToGame_ToolTip {
            get {
                return ResourceManager.GetString("CommandBar_Button_ExportOrderToGame_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Game....
        /// </summary>
        public static string CommandBar_Button_LaunchGame_ToolTip {
            get {
                return ResourceManager.GetString("CommandBar_Button_LaunchGame_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Mod Locations\nInactive mods will be moved to Mods_Disabled, and active mods will be moved to the Mods folder..
        /// </summary>
        public static string CommandBar_Button_MoveMods_ToolTip {
            get {
                return ResourceManager.GetString("CommandBar_Button_MoveMods_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Script Extender Logs Folder....
        /// </summary>
        public static string CommandBar_Button_OpenExtenderLogsFolder_ToolTip {
            get {
                return ResourceManager.GetString("CommandBar_Button_OpenExtenderLogsFolder_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Home Page (GitHub)....
        /// </summary>
        public static string CommandBar_Button_OpenGitHub_ToolTip {
            get {
                return ResourceManager.GetString("CommandBar_Button_OpenGitHub_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mods Folder....
        /// </summary>
        public static string CommandBar_Button_OpenModsFolder_ToolTip {
            get {
                return ResourceManager.GetString("CommandBar_Button_OpenModsFolder_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Nexus Mods....
        /// </summary>
        public static string CommandBar_Button_OpenNexusMods_ToolTip {
            get {
                return ResourceManager.GetString("CommandBar_Button_OpenNexusMods_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Steam Page....
        /// </summary>
        public static string CommandBar_Button_OpenSteamPage_ToolTip {
            get {
                return ResourceManager.GetString("CommandBar_Button_OpenSteamPage_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Mods.
        /// </summary>
        public static string CommandBar_Button_RefreshMods_ToolTip {
            get {
                return ResourceManager.GetString("CommandBar_Button_RefreshMods_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Order.
        /// </summary>
        public static string CommandBar_Button_SaveOrder_ToolTip {
            get {
                return ResourceManager.GetString("CommandBar_Button_SaveOrder_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Order As....
        /// </summary>
        public static string CommandBar_Button_SaveOrderAs_ToolTip {
            get {
                return ResourceManager.GetString("CommandBar_Button_SaveOrderAs_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Executable Path....
        /// </summary>
        public static string CommandBar_LaunchGameFlyout_Button_EditExecutablePath {
            get {
                return ResourceManager.GetString("CommandBar_LaunchGameFlyout_Button_EditExecutablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Parent Folder in Directory Opus....
        /// </summary>
        public static string CommandBar_LaunchGameFlyout_Button_OpenGameFolder_Dopus {
            get {
                return ResourceManager.GetString("CommandBar_LaunchGameFlyout_Button_OpenGameFolder_Dopus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Parent Folder in File Explorer....
        /// </summary>
        public static string CommandBar_LaunchGameFlyout_Button_OpenGameFolder_FileExplorer {
            get {
                return ResourceManager.GetString("CommandBar_LaunchGameFlyout_Button_OpenGameFolder_FileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable Path.
        /// </summary>
        public static string CommandBar_LaunchGameFlyout_CopyToClipboard_Button_ExecutablePath {
            get {
                return ResourceManager.GetString("CommandBar_LaunchGameFlyout_CopyToClipboard_Button_ExecutablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Folder Path.
        /// </summary>
        public static string CommandBar_LaunchGameFlyout_CopyToClipboard_Button_ParentFolder {
            get {
                return ResourceManager.GetString("CommandBar_LaunchGameFlyout_CopyToClipboard_Button_ParentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard....
        /// </summary>
        public static string CommandBar_LaunchGameFlyout_CopyToClipboard_Header {
            get {
                return ResourceManager.GetString("CommandBar_LaunchGameFlyout_CopyToClipboard_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string CommandBar_LaunchGameFlyout_Open_Header {
            get {
                return ResourceManager.GetString("CommandBar_LaunchGameFlyout_Open_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile....
        /// </summary>
        public static string CommandBar_ProfileFlyout_Profile_Header {
            get {
                return ResourceManager.GetString("CommandBar_ProfileFlyout_Profile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves....
        /// </summary>
        public static string CommandBar_ProfileFlyout_Saves_Header {
            get {
                return ResourceManager.GetString("CommandBar_ProfileFlyout_Saves_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign.
        /// </summary>
        public static string CommandBar_Section_Campaign {
            get {
                return ResourceManager.GetString("CommandBar_Section_Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string CommandBar_Section_Export {
            get {
                return ResourceManager.GetString("CommandBar_Section_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string CommandBar_Section_Links {
            get {
                return ResourceManager.GetString("CommandBar_Section_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string CommandBar_Section_Order {
            get {
                return ResourceManager.GetString("CommandBar_Section_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string CommandBar_Section_Profile {
            get {
                return ResourceManager.GetString("CommandBar_Section_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string CommandBar_Section_Refresh {
            get {
                return ResourceManager.GetString("CommandBar_Section_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        public static string CommandBar_Section_Shortcuts {
            get {
                return ResourceManager.GetString("CommandBar_Section_Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string CommandBar_Section_Support {
            get {
                return ResourceManager.GetString("CommandBar_Section_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NexusMods API Limit [Hourly ({0}/{1}) Daily ({2}/{3})].
        /// </summary>
        public static string Footer_NexusModsAPILimit_Text {
            get {
                return ResourceManager.GetString("Footer_NexusModsAPILimit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nexus Mods API Limits.
        /// </summary>
        public static string Footer_NexusModsAPILimit_ToolTip {
            get {
                return ResourceManager.GetString("Footer_NexusModsAPILimit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larian Studios.
        /// </summary>
        public static string LarianStudios {
            get {
                return ResourceManager.GetString("LarianStudios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Mod Display Name.
        /// </summary>
        public static string Mod_Command_DisplayFileForName_Disable {
            get {
                return ResourceManager.GetString("Mod_Command_DisplayFileForName_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show File Name.
        /// </summary>
        public static string Mod_Command_DisplayFileForName_Enable {
            get {
                return ResourceManager.GetString("Mod_Command_DisplayFileForName_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Load Order.
        /// </summary>
        public static string Mod_Command_ForceAllowInLoadOrder_Disable {
            get {
                return ResourceManager.GetString("Mod_Command_ForceAllowInLoadOrder_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow in Load Order.
        /// </summary>
        public static string Mod_Command_ForceAllowInLoadOrder_Enable {
            get {
                return ResourceManager.GetString("Mod_Command_ForceAllowInLoadOrder_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string Mod_DisplayName_FileView_Pattern {
            get {
                return ResourceManager.GetString("Mod_DisplayName_FileView_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Loose Mod].
        /// </summary>
        public static string Mod_DisplayName_FileView_Type_Loose {
            get {
                return ResourceManager.GetString("Mod_DisplayName_FileView_Type_Loose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Toolkit Project].
        /// </summary>
        public static string Mod_DisplayName_FileView_Type_Toolkit {
            get {
                return ResourceManager.GetString("Mod_DisplayName_FileView_Type_Toolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Enable Extensions in the Script Extender Settings).
        /// </summary>
        public static string Mod_ExtenderStatus_DisabledFromConfig {
            get {
                return ResourceManager.GetString("Mod_ExtenderStatus_DisabledFromConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently installed version is v{0}.
        /// </summary>
        public static string Mod_ExtenderStatus_InstalledVersion {
            get {
                return ResourceManager.GetString("Mod_ExtenderStatus_InstalledVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Missing %LOCALAPPDATA%\\..\\{0}).
        /// </summary>
        public static string Mod_ExtenderStatus_MissingAppData {
            get {
                return ResourceManager.GetString("Mod_ExtenderStatus_MissingAppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (The installed SE version is older).
        /// </summary>
        public static string Mod_ExtenderStatus_MissingRequiredVersion {
            get {
                return ResourceManager.GetString("Mod_ExtenderStatus_MissingRequiredVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Missing {0}).
        /// </summary>
        public static string Mod_ExtenderStatus_MissingUpdater {
            get {
                return ResourceManager.GetString("Mod_ExtenderStatus_MissingUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are missing the Script Extender updater (DWrite.dll), which is required.
        /// </summary>
        public static string Mod_ExtenderStatus_MissingUpdaterInfo {
            get {
                return ResourceManager.GetString("Mod_ExtenderStatus_MissingUpdaterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No installed Script Extender version found\nIf you&apos;ve already downloaded it, try opening the game once to complete the installation process.
        /// </summary>
        public static string Mod_ExtenderStatus_NotFoundInfo {
            get {
                return ResourceManager.GetString("Mod_ExtenderStatus_NotFoundInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires the Script Extender.
        /// </summary>
        public static string Mod_ExtenderStatus_RequiresDefault {
            get {
                return ResourceManager.GetString("Mod_ExtenderStatus_RequiresDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires Script Extender v{0} or Higher.
        /// </summary>
        public static string Mod_ExtenderStatus_RequiresVersion {
            get {
                return ResourceManager.GetString("Mod_ExtenderStatus_RequiresVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Dependencies:\n{0}.
        /// </summary>
        public static string Mod_MissingDependenciesToolTip {
            get {
                return ResourceManager.GetString("Mod_MissingDependenciesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on {0}.
        /// </summary>
        public static string Mod_NexusModsToolTip_CreatedOn {
            get {
                return ResourceManager.GetString("Mod_NexusModsToolTip_CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsements: {0}.
        /// </summary>
        public static string Mod_NexusModsToolTip_Endorsements {
            get {
                return ResourceManager.GetString("Mod_NexusModsToolTip_Endorsements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated on {0}.
        /// </summary>
        public static string Mod_NexusModsToolTip_UpdatedOn {
            get {
                return ResourceManager.GetString("Mod_NexusModsToolTip_UpdatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Mod Fixer.
        /// </summary>
        public static string Mod_OsirisStatus_HasModFixer {
            get {
                return ResourceManager.GetString("Mod_OsirisStatus_HasModFixer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Osiris Scripting.
        /// </summary>
        public static string Mod_OsirisStatus_HasScripts {
            get {
                return ResourceManager.GetString("Mod_OsirisStatus_HasScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name({0}) Version({1}) Author({2}) UUID({3}) File({4}).
        /// </summary>
        public static string Mod_StringFormatPattern {
            get {
                return ResourceManager.GetString("Mod_StringFormatPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-on.
        /// </summary>
        public static string Mod_Type_Addon {
            get {
                return ResourceManager.GetString("Mod_Type_Addon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure.
        /// </summary>
        public static string Mod_Type_Adventure {
            get {
                return ResourceManager.GetString("Mod_Type_Adventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loose Mod.
        /// </summary>
        public static string Mod_Type_LooseMod {
            get {
                return ResourceManager.GetString("Mod_Type_LooseMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override.
        /// </summary>
        public static string Mod_Type_Override {
            get {
                return ResourceManager.GetString("Mod_Type_Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pak.
        /// </summary>
        public static string Mod_Type_Pak {
            get {
                return ResourceManager.GetString("Mod_Type_Pak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit Project.
        /// </summary>
        public static string Mod_Type_ToolkitProject {
            get {
                return ResourceManager.GetString("Mod_Type_ToolkitProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container ({0} Children).
        /// </summary>
        public static string ModContainer_ToolTip_Children {
            get {
                return ResourceManager.GetString("ModContainer_ToolTip_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Container....
        /// </summary>
        public static string ModListView_AddContainer {
            get {
                return ResourceManager.GetString("ModListView_AddContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container....
        /// </summary>
        public static string ModListView_DeleteContainer {
            get {
                return ResourceManager.GetString("ModListView_DeleteContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Mods....
        /// </summary>
        public static string ModListView_DeleteContainerMods {
            get {
                return ResourceManager.GetString("ModListView_DeleteContainerMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename....
        /// </summary>
        public static string ModListView_RenameContainer {
            get {
                return ResourceManager.GetString("ModListView_RenameContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Game Launch.
        /// </summary>
        public static string Settings_ActionOnGameLaunch_Header {
            get {
                return ResourceManager.GetString("Settings_ActionOnGameLaunch_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the game launches through the mod manager, this action will be performed on the mod manager window.
        /// </summary>
        public static string Settings_ActionOnGameLaunch_Header_ToolTip {
            get {
                return ResourceManager.GetString("Settings_ActionOnGameLaunch_Header_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Settings_ActionOnGameLaunch_Value_Close {
            get {
                return ResourceManager.GetString("Settings_ActionOnGameLaunch_Value_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the window.
        /// </summary>
        public static string Settings_ActionOnGameLaunch_Value_Close_ToolTip {
            get {
                return ResourceManager.GetString("Settings_ActionOnGameLaunch_Value_Close_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Settings_ActionOnGameLaunch_Value_Minimize {
            get {
                return ResourceManager.GetString("Settings_ActionOnGameLaunch_Value_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize the window.
        /// </summary>
        public static string Settings_ActionOnGameLaunch_Value_Minimize_ToolTip {
            get {
                return ResourceManager.GetString("Settings_ActionOnGameLaunch_Value_Minimize_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Settings_ActionOnGameLaunch_Value_None {
            get {
                return ResourceManager.GetString("Settings_ActionOnGameLaunch_Value_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do nothing.
        /// </summary>
        public static string Settings_ActionOnGameLaunch_Value_None_ToolTip {
            get {
                return ResourceManager.GetString("Settings_ActionOnGameLaunch_Value_None_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Window_About_Title {
            get {
                return ResourceManager.GetString("Window_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string Window_About_Title_Author {
            get {
                return ResourceManager.GetString("Window_About_Title_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog:.
        /// </summary>
        public static string Window_About_Title_Changelog {
            get {
                return ResourceManager.GetString("Window_About_Title_Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate a Coffee:.
        /// </summary>
        public static string Window_About_Title_Donate {
            get {
                return ResourceManager.GetString("Window_About_Title_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page:.
        /// </summary>
        public static string Window_About_Title_HomePage {
            get {
                return ResourceManager.GetString("Window_About_Title_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an Issue:.
        /// </summary>
        public static string Window_About_Title_Issues {
            get {
                return ResourceManager.GetString("Window_About_Title_Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License:.
        /// </summary>
        public static string Window_About_Title_License {
            get {
                return ResourceManager.GetString("Window_About_Title_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Links.
        /// </summary>
        public static string Window_About_Title_SupportLinks {
            get {
                return ResourceManager.GetString("Window_About_Title_SupportLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} is now available.\nYou have version {2} installed..
        /// </summary>
        public static string Window_AppUpdate_Available {
            get {
                return ResourceManager.GetString("Window_AppUpdate_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string Window_AppUpdate_ChangelogTitle {
            get {
                return ResourceManager.GetString("Window_AppUpdate_ChangelogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and install the latest update..
        /// </summary>
        public static string Window_AppUpdate_DownloadToolTip {
            get {
                return ResourceManager.GetString("Window_AppUpdate_DownloadToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Window_AppUpdate_Title {
            get {
                return ResourceManager.GetString("Window_AppUpdate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0] is up-to-date..
        /// </summary>
        public static string Window_AppUpdate_UpToDate {
            get {
                return ResourceManager.GetString("Window_AppUpdate_UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View as Cards.
        /// </summary>
        public static string Window_CollectionDownloader_Button_CardView_ToolTip {
            get {
                return ResourceManager.GetString("Window_CollectionDownloader_Button_CardView_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable All.
        /// </summary>
        public static string Window_CollectionDownloader_Button_DisableAll_ToolTip {
            get {
                return ResourceManager.GetString("Window_CollectionDownloader_Button_DisableAll_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable All.
        /// </summary>
        public static string Window_CollectionDownloader_Button_EnableAll_ToolTip {
            get {
                return ResourceManager.GetString("Window_CollectionDownloader_Button_EnableAll_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View as List.
        /// </summary>
        public static string Window_CollectionDownloader_Button_ListView_ToolTip {
            get {
                return ResourceManager.GetString("Window_CollectionDownloader_Button_ListView_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download {0}.
        /// </summary>
        public static string Window_CollectionDownloader_Heading_ModOnly {
            get {
                return ResourceManager.GetString("Window_CollectionDownloader_Heading_ModOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Collection.
        /// </summary>
        public static string Window_CollectionDownloader_Heading_Unknown {
            get {
                return ResourceManager.GetString("Window_CollectionDownloader_Heading_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download {0} by {1}.
        /// </summary>
        public static string Window_CollectionDownloader_Heading_WithAuthor {
            get {
                return ResourceManager.GetString("Window_CollectionDownloader_Heading_WithAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods.
        /// </summary>
        public static string Window_CollectionDownloader_Section_Mods {
            get {
                return ResourceManager.GetString("Window_CollectionDownloader_Section_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NexusMods Collection Downloader.
        /// </summary>
        public static string Window_CollectionDownloader_Title {
            get {
                return ResourceManager.GetString("Window_CollectionDownloader_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Window_ModProperties_Section_Description {
            get {
                return ResourceManager.GetString("Window_ModProperties_Section_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string Window_ModProperties_Section_Location {
            get {
                return ResourceManager.GetString("Window_ModProperties_Section_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod type:.
        /// </summary>
        public static string Window_ModProperties_Section_ModType {
            get {
                return ResourceManager.GetString("Window_ModProperties_Section_ModType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Window_ModProperties_Section_Name {
            get {
                return ResourceManager.GetString("Window_ModProperties_Section_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string Window_ModProperties_Section_Size {
            get {
                return ResourceManager.GetString("Window_ModProperties_Section_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string Window_ModProperties_Tab_Config {
            get {
                return ResourceManager.GetString("Window_ModProperties_Tab_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Window_ModProperties_Tab_General {
            get {
                return ResourceManager.GetString("Window_ModProperties_Tab_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Window_ModProperties_Tab_Notes {
            get {
                return ResourceManager.GetString("Window_ModProperties_Tab_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Properties.
        /// </summary>
        public static string Window_ModProperties_Title {
            get {
                return ResourceManager.GetString("Window_ModProperties_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Properties.
        /// </summary>
        public static string Window_ModProperties_TitleWithMod {
            get {
                return ResourceManager.GetString("Window_ModProperties_TitleWithMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a nxm:\\ url below:.
        /// </summary>
        public static string Window_NXMDownload_Instructions {
            get {
                return ResourceManager.GetString("Window_NXMDownload_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NXM Downloader.
        /// </summary>
        public static string Window_NXMDownload_Title {
            get {
                return ResourceManager.GetString("Window_NXMDownload_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mod(s)....
        /// </summary>
        public static string Window_PakFileExplorer_MenuItem_AddMods_ToolTip {
            get {
                return ResourceManager.GetString("Window_PakFileExplorer_MenuItem_AddMods_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Pak....
        /// </summary>
        public static string Window_PakFileExplorer_MenuItem_AddPak_ToolTip {
            get {
                return ResourceManager.GetString("Window_PakFileExplorer_MenuItem_AddPak_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string Window_PakFileExplorer_MenuItem_ClearAll_ToolTip {
            get {
                return ResourceManager.GetString("Window_PakFileExplorer_MenuItem_ClearAll_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract All Selected To....
        /// </summary>
        public static string Window_PakFileExplorer_MenuItem_ExtractAllTo {
            get {
                return ResourceManager.GetString("Window_PakFileExplorer_MenuItem_ExtractAllTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract To....
        /// </summary>
        public static string Window_PakFileExplorer_MenuItem_ExtractTo {
            get {
                return ResourceManager.GetString("Window_PakFileExplorer_MenuItem_ExtractTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Mods to View....
        /// </summary>
        public static string Window_PakFileExplorer_Picker_AddMod_Title {
            get {
                return ResourceManager.GetString("Window_PakFileExplorer_Picker_AddMod_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Pak File....
        /// </summary>
        public static string Window_PakFileExplorer_Picker_AddPak_Title {
            get {
                return ResourceManager.GetString("Window_PakFileExplorer_Picker_AddPak_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract File(s) To....
        /// </summary>
        public static string Window_PakFileExplorer_Picker_ExtractFiles_Title {
            get {
                return ResourceManager.GetString("Window_PakFileExplorer_Picker_ExtractFiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod File Explorer.
        /// </summary>
        public static string Window_PakFileExplorer_Title {
            get {
                return ResourceManager.GetString("Window_PakFileExplorer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation complete for {0}.
        /// </summary>
        public static string Window_StatsValidator_Alert_Done {
            get {
                return ResourceManager.GetString("Window_StatsValidator_Alert_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing base data....
        /// </summary>
        public static string Window_StatsValidator_Alert_Init {
            get {
                return ResourceManager.GetString("Window_StatsValidator_Alert_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating mod stats....
        /// </summary>
        public static string Window_StatsValidator_Alert_Validating {
            get {
                return ResourceManager.GetString("Window_StatsValidator_Alert_Validating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Again.
        /// </summary>
        public static string Window_StatsValidator_Button_Validate_ToolTip {
            get {
                return ResourceManager.GetString("Window_StatsValidator_Button_Validate_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Window_StatsValidator_FileUnknown {
            get {
                return ResourceManager.GetString("Window_StatsValidator_FileUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating....
        /// </summary>
        public static string Window_StatsValidator_LockScreen_Text {
            get {
                return ResourceManager.GetString("Window_StatsValidator_LockScreen_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} issue(s):.
        /// </summary>
        public static string Window_StatsValidator_Output_Issues {
            get {
                return ResourceManager.GetString("Window_StatsValidator_Output_Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No issues found!.
        /// </summary>
        public static string Window_StatsValidator_Output_NoIssues {
            get {
                return ResourceManager.GetString("Window_StatsValidator_Output_NoIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Window_StatsValidator_Section_Results {
            get {
                return ResourceManager.GetString("Window_StatsValidator_Section_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Taken:.
        /// </summary>
        public static string Window_StatsValidator_Section_TimeTaken {
            get {
                return ResourceManager.GetString("Window_StatsValidator_Section_TimeTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats Validator.
        /// </summary>
        public static string Window_StatsValidator_Title {
            get {
                return ResourceManager.GetString("Window_StatsValidator_Title", resourceCulture);
            }
        }
    }
}
