//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModManager.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModManager.Locale.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Button_Download {
            get {
                return ResourceManager.GetString("Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Button_Skip {
            get {
                return ResourceManager.GetString("Button_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NexusMods API Limit [Hourly ({0}/{1}) Daily ({2}/{3})].
        /// </summary>
        public static string Footer_NexusModsAPILimit_Text {
            get {
                return ResourceManager.GetString("Footer_NexusModsAPILimit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nexus Mods API Limits.
        /// </summary>
        public static string Footer_NexusModsAPILimit_ToolTip {
            get {
                return ResourceManager.GetString("Footer_NexusModsAPILimit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larian Studios.
        /// </summary>
        public static string LarianStudios {
            get {
                return ResourceManager.GetString("LarianStudios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Mod Display Name.
        /// </summary>
        public static string Mod_Command_DisplayFileForName_Disable {
            get {
                return ResourceManager.GetString("Mod_Command_DisplayFileForName_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show File Name.
        /// </summary>
        public static string Mod_Command_DisplayFileForName_Enable {
            get {
                return ResourceManager.GetString("Mod_Command_DisplayFileForName_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Load Order.
        /// </summary>
        public static string Mod_Command_ForceAllowInLoadOrder_Disable {
            get {
                return ResourceManager.GetString("Mod_Command_ForceAllowInLoadOrder_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow in Load Order.
        /// </summary>
        public static string Mod_Command_ForceAllowInLoadOrder_Enable {
            get {
                return ResourceManager.GetString("Mod_Command_ForceAllowInLoadOrder_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string Mod_DisplayName_FileView_Pattern {
            get {
                return ResourceManager.GetString("Mod_DisplayName_FileView_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Loose Mod].
        /// </summary>
        public static string Mod_DisplayName_FileView_Type_Loose {
            get {
                return ResourceManager.GetString("Mod_DisplayName_FileView_Type_Loose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Toolkit Project].
        /// </summary>
        public static string Mod_DisplayName_FileView_Type_Toolkit {
            get {
                return ResourceManager.GetString("Mod_DisplayName_FileView_Type_Toolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Enable Extensions in the Script Extender Settings).
        /// </summary>
        public static string Mod_ExtenderStatus_DisabledFromConfig {
            get {
                return ResourceManager.GetString("Mod_ExtenderStatus_DisabledFromConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently installed version is v{0}.
        /// </summary>
        public static string Mod_ExtenderStatus_InstalledVersion {
            get {
                return ResourceManager.GetString("Mod_ExtenderStatus_InstalledVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Missing %LOCALAPPDATA%\\..\\{0}).
        /// </summary>
        public static string Mod_ExtenderStatus_MissingAppData {
            get {
                return ResourceManager.GetString("Mod_ExtenderStatus_MissingAppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (The installed SE version is older).
        /// </summary>
        public static string Mod_ExtenderStatus_MissingRequiredVersion {
            get {
                return ResourceManager.GetString("Mod_ExtenderStatus_MissingRequiredVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Missing {0}).
        /// </summary>
        public static string Mod_ExtenderStatus_MissingUpdater {
            get {
                return ResourceManager.GetString("Mod_ExtenderStatus_MissingUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are missing the Script Extender updater (DWrite.dll), which is required.
        /// </summary>
        public static string Mod_ExtenderStatus_MissingUpdaterInfo {
            get {
                return ResourceManager.GetString("Mod_ExtenderStatus_MissingUpdaterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No installed Script Extender version found\nIf you&apos;ve already downloaded it, try opening the game once to complete the installation process.
        /// </summary>
        public static string Mod_ExtenderStatus_NotFoundInfo {
            get {
                return ResourceManager.GetString("Mod_ExtenderStatus_NotFoundInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires the Script Extender.
        /// </summary>
        public static string Mod_ExtenderStatus_RequiresDefault {
            get {
                return ResourceManager.GetString("Mod_ExtenderStatus_RequiresDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires Script Extender v{0} or Higher.
        /// </summary>
        public static string Mod_ExtenderStatus_RequiresVersion {
            get {
                return ResourceManager.GetString("Mod_ExtenderStatus_RequiresVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Dependencies:\n{0}.
        /// </summary>
        public static string Mod_MissingDependenciesToolTip {
            get {
                return ResourceManager.GetString("Mod_MissingDependenciesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on {0}.
        /// </summary>
        public static string Mod_NexusModsToolTip_CreatedOn {
            get {
                return ResourceManager.GetString("Mod_NexusModsToolTip_CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsements: {0}.
        /// </summary>
        public static string Mod_NexusModsToolTip_Endorsements {
            get {
                return ResourceManager.GetString("Mod_NexusModsToolTip_Endorsements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated on {0}.
        /// </summary>
        public static string Mod_NexusModsToolTip_UpdatedOn {
            get {
                return ResourceManager.GetString("Mod_NexusModsToolTip_UpdatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Mod Fixer.
        /// </summary>
        public static string Mod_OsirisStatus_HasModFixer {
            get {
                return ResourceManager.GetString("Mod_OsirisStatus_HasModFixer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Osiris Scripting.
        /// </summary>
        public static string Mod_OsirisStatus_HasScripts {
            get {
                return ResourceManager.GetString("Mod_OsirisStatus_HasScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name({0}) Version({1}) Author({2}) UUID({3}) File({4}).
        /// </summary>
        public static string Mod_StringFormatPattern {
            get {
                return ResourceManager.GetString("Mod_StringFormatPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-on.
        /// </summary>
        public static string Mod_Type_Addon {
            get {
                return ResourceManager.GetString("Mod_Type_Addon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure.
        /// </summary>
        public static string Mod_Type_Adventure {
            get {
                return ResourceManager.GetString("Mod_Type_Adventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loose Mod.
        /// </summary>
        public static string Mod_Type_LooseMod {
            get {
                return ResourceManager.GetString("Mod_Type_LooseMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override.
        /// </summary>
        public static string Mod_Type_Override {
            get {
                return ResourceManager.GetString("Mod_Type_Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit Project.
        /// </summary>
        public static string Mod_Type_ToolkitProject {
            get {
                return ResourceManager.GetString("Mod_Type_ToolkitProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Window_About_Title {
            get {
                return ResourceManager.GetString("Window_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string Window_About_Title_Author {
            get {
                return ResourceManager.GetString("Window_About_Title_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog:.
        /// </summary>
        public static string Window_About_Title_Changelog {
            get {
                return ResourceManager.GetString("Window_About_Title_Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate a Coffee:.
        /// </summary>
        public static string Window_About_Title_Donate {
            get {
                return ResourceManager.GetString("Window_About_Title_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page:.
        /// </summary>
        public static string Window_About_Title_HomePage {
            get {
                return ResourceManager.GetString("Window_About_Title_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an Issue:.
        /// </summary>
        public static string Window_About_Title_Issues {
            get {
                return ResourceManager.GetString("Window_About_Title_Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License:.
        /// </summary>
        public static string Window_About_Title_License {
            get {
                return ResourceManager.GetString("Window_About_Title_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Links.
        /// </summary>
        public static string Window_About_Title_SupportLinks {
            get {
                return ResourceManager.GetString("Window_About_Title_SupportLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} is now available.\nYou have version {2} installed..
        /// </summary>
        public static string Window_AppUpdate_Available {
            get {
                return ResourceManager.GetString("Window_AppUpdate_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string Window_AppUpdate_ChangelogTitle {
            get {
                return ResourceManager.GetString("Window_AppUpdate_ChangelogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and install the latest update..
        /// </summary>
        public static string Window_AppUpdate_DownloadToolTip {
            get {
                return ResourceManager.GetString("Window_AppUpdate_DownloadToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Window_AppUpdate_Title {
            get {
                return ResourceManager.GetString("Window_AppUpdate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0] is up-to-date..
        /// </summary>
        public static string Window_AppUpdate_UpToDate {
            get {
                return ResourceManager.GetString("Window_AppUpdate_UpToDate", resourceCulture);
            }
        }
    }
}
